// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blog" | "/blog/[slug]" | "/cookies" | "/dashboard" | "/offline" | "/practice" | "/practice/[testId]" | "/practice/[testId]/results" | "/practice/smart" | "/practice/smart/session" | "/privacy" | "/study" | "/study/[topicId]" | "/terms"
type AppRouteHandlerRoutes = "/api/abs-population" | "/api/australia-insights" | "/api/chat" | "/api/checkout" | "/api/generate-image" | "/api/webhooks/stripe"
type PageRoutes = never
type LayoutRoutes = "/" | "/blog" | "/dashboard" | "/offline" | "/practice" | "/practice/[testId]" | "/practice/smart" | "/study"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/abs-population": {}
  "/api/australia-insights": {}
  "/api/chat": {}
  "/api/checkout": {}
  "/api/generate-image": {}
  "/api/webhooks/stripe": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/cookies": {}
  "/dashboard": {}
  "/offline": {}
  "/practice": {}
  "/practice/[testId]": { "testId": string; }
  "/practice/[testId]/results": { "testId": string; }
  "/practice/smart": {}
  "/practice/smart/session": {}
  "/privacy": {}
  "/study": {}
  "/study/[topicId]": { "topicId": string; }
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/blog": never
  "/dashboard": never
  "/offline": never
  "/practice": never
  "/practice/[testId]": never
  "/practice/smart": never
  "/study": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
